version: '3.7'
services:
  raise_exception:
    image: raiseexception_web
    build:
      target: raiseexception_web
    environment:
      - APP_ENVIRONMENT=production

  db:
    ports:
      - "0:5432"
