version: '3.7'
services:
  raise_exception:
    image: raise_exception_dev
    build:
      target: testing
    volumes:
      - .:/code/
    ports:
      - "0:8000"
    environment:
      - APP_ENVIRONMENT=dev

  db:
    ports:
      - "0:5432"
