version: 2
jobs:
  web:
    docker:
      - image: juliancortes77/raiseexception:dev
        auth:
          username: juliancortes77
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/nyoibo
    steps:
      - checkout
      - run:
          name: xenon
          command: sh run_xenon.sh
      - run:
          name: run tests
          command: sh run_tests.sh

workflows:
  version: 2
  test:
    jobs:
      - web
