version: 2
jobs:
  web:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/nyoibo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements_dev.txt -r requirements.txt
      - run:
          name: xenon
          command: sh run_xenon.sh
      - run:
          name: run tests
          command: sh run_tests.sh

workflows:
  version: 2
  test:
    jobs:
      - web
