version: 2
jobs:
  web:
    docker:
      - image: juliancortes77/raiseexception:latest
        auth:
          username: juliancortes77
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: xenon
          command: sh run_xenon.sh
      - run:
          name: run tests
          command: sh run_tests.sh

workflows:
  version: 2
  test:
    jobs:
      - web
